---
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: "yes"

- name: Set the timezone
  community.general.timezone:
    name: US/Eastern

- name: Add a user
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: sudo
    append: "yes"
    password: "{{ user_name_password }}"

- name: Set the root password
  ansible.builtin.user:
    name: root
    append: "yes"
    password: "{{ root_password }}"

- name: Create swap file
  ansible.builtin.command: dd if=/dev/zero of=/swapfile bs=1M count={{swap_file_size}} status=progress

- name: Set swap file permissions
  ansible.builtin.file:
    path: /swapfile
    owner: root
    group: root
    mode: "0677"

- name: Set file as swap file
  ansible.builtin.command: mkswap /swapfile

- name: Turn on swapfile
  ansible.builtin.command: swapon /swapfile

- name: Add swapfile to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: /swapfile none swap defaults 0 0
    create: "yes"

- name: Allow ssh
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    source: "{{ network_prefix }}"
    in_interface: "{{ interface_name }}"
    limit: 6/minute
    jump: ACCEPT
  become: "yes"

- name: Allow ssh ipv6
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    source: "fe80::/10"
    in_interface: "{{ interface_name }}"
    limit: 6/minute
    jump: ACCEPT
    ip_version: ipv6
  become: "yes"

- name: Allow icmp
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    source: "{{ network_prefix }}"
    in_interface: "{{ interface_name }}"
    jump: ACCEPT
  become: "yes"

- name: Allow icmpv6
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmpv6
    source: "fe80::/10"
    in_interface: "{{ interface_name }}"
    jump: ACCEPT
    ip_version: ipv6
  become: "yes"

- name: Allow loopback
  ansible.builtin.iptables:
    chain: INPUT
    source: "127.0.0.1"
    in_interface: lo
    jump: ACCEPT
  become: "yes"

- name: Allow loopback ipv6
  ansible.builtin.iptables:
    chain: INPUT
    source: "::1"
    in_interface: lo
    jump: ACCEPT
    ip_version: ipv6
  become: "yes"

- name: Allow established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: "yes"

- name: Drop inbound by default
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Allow outbound by default
  ansible.builtin.iptables:
    chain: OUTPUT
    policy: ACCEPT

- name: Drop forwarding by default
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP

- name: Allow established connections ipv6
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    ip_version: ipv6
  become: "yes"

- name: Drop inbound by default ipv6
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
    ip_version: ipv6

- name: Allow outbound by default ipv6
  ansible.builtin.iptables:
    chain: OUTPUT
    policy: ACCEPT
    ip_version: ipv6

- name: Drop forwarding by default ipv6
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP
    ip_version: ipv6

- name: Save Iptables Rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4

- name: Save Iptables Rules ipv6
  ansible.builtin.shell: ip6tables-save > /etc/iptables/rules.v6

- name: Hosts file configuration
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"

- name: Hostname file configuration
  ansible.builtin.template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: "0644"

- name: Network interfaces configuration
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: "0644"

- name: locale configuration
  ansible.builtin.template:
    src: locale.j2
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: "0644"

- name: SSH configuration
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
