---
- name: Hosts file configuration
  ansible.builtin.template:
    src: /mytemplates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"

- name: Hostname file configuration
  ansible.builtin.template:
    src: /mytemplates/hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: "0644"

- name: Network interfaces configuration
  ansible.builtin.template:
    src: /mytemplates/interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: "0644"

- name: locale configuration
  ansible.builtin.template:
    src: /mytemplates/locale.j2
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: "0644"
