---
- name: Update Debian servers weekly
  ansible.builtin.cron:
    name: "Update Debian Servers"
    minute: "0"
    hour: "0"
    weekday: "0"
    job: "ansible-playbook /etc/ansible/apt_update_server.yml"

- name: Reboot DNS Containers at reboot
  ansible.builtin.cron:
    name: "Reboot DNS Containers"
    special_time: reboot
    job: "ansible-playbook /etc/ansible/reboot_dns_containers.yml"

- name: Clone Ansible Repo
  ansible.builtin.git:
    repo: https://github.com/MatthewDavidMiller/ansible_configuration.git
    dest: "/ansible_configs/git/ansible_configuration"

- name: Clone Dns Repo
  ansible.builtin.git:
    repo: https://github.com/MatthewDavidMiller/DNS-Server-Configuration.git
    dest: "/ansible_configs/git/DNS-Server-Configuration"

- name: Clone VPN Repo
  ansible.builtin.git:
    repo: https://github.com/MatthewDavidMiller/VPN-Server-Configuration.git
    dest: "/ansible_configs/git/VPN-Server-Configuration"
