---
- name: Standard Tasks
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: latest

    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      community.crypto.openssh_keypair:
        path: "/home/{{user_name}}/{{key_name}}"
        type: ed25519

    - name: Create swap file
      ansible.builtin.command: dd if=/dev/zero of=/swapfile bs=1M count={{swap_file_size}} status=progress

    - name: Set swap file permissions
      ansible.builtin.file:
        path: /swapfile
        owner: root
        group: root
        mode: "0677"

    - name: Set file as swap file
      ansible.builtin.command: mkswap of=/swapfile

    - name: Turn on swapfile
      ansible.builtin.command: swapon of=/swapfile

    - name: Add swapfile to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: /swapfile none swap defaults 0 0
        create: "yes"

    - name: Allow ssh
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "22"
        source: "{{ network_prefix }}"
        in_interface: "{{ interface_name }}"
        limit: 6/minute
        jump: ACCEPT
      become: "yes"

    - name: Allow ssh ipv6
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "22"
        source: "fe80::/10"
        in_interface: "{{ interface_name }}"
        limit: 6/minute
        jump: ACCEPT
        ip_version: ipv6
      become: "yes"

    - name: Allow icmp
      ansible.builtin.iptables:
        chain: INPUT
        protocol: icmp
        source: "{{ network_prefix }}"
        in_interface: "{{ interface_name }}"
        jump: ACCEPT
      become: "yes"

    - name: Allow icmpv6
      ansible.builtin.iptables:
        chain: INPUT
        protocol: icmpv6
        source: "fe80::/10"
        in_interface: "{{ interface_name }}"
        jump: ACCEPT
        ip_version: ipv6
      become: "yes"

    - name: Allow loopback
      ansible.builtin.iptables:
        chain: INPUT
        source: "127.0.0.1"
        in_interface: lo
        jump: ACCEPT
      become: "yes"

    - name: Allow loopback ipv6
      ansible.builtin.iptables:
        chain: INPUT
        source: "::1"
        in_interface: lo
        jump: ACCEPT
        ip_version: ipv6
      become: "yes"

    - name: Allow established connections
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
      become: "yes"

    - name: Drop inbound by default
      ansible.builtin.iptables:
        chain: INPUT
        policy: DROP

    - name: Allow outbound by default
      ansible.builtin.iptables:
        chain: OUTPUT
        policy: ACCEPT

    - name: Drop forwarding by default
      ansible.builtin.iptables:
        chain: FORWARD
        policy: DROP

    - name: Allow established connections ipv6
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
        ip_version: ipv6
      become: "yes"

    - name: Drop inbound by default ipv6
      ansible.builtin.iptables:
        chain: INPUT
        policy: DROP
        ip_version: ipv6

    - name: Allow outbound by default ipv6
      ansible.builtin.iptables:
        chain: OUTPUT
        policy: ACCEPT
        ip_version: ipv6

    - name: Drop forwarding by default ipv6
      ansible.builtin.iptables:
        chain: FORWARD
        policy: DROP
        ip_version: ipv6
