---
- name: Update Debian servers weekly
  ansible.builtin.cron:
    name: "Update Debian Servers"
    minute: "0"
    hour: "0"
    weekday: "0"
    job: "ansible-playbook {{ standalone_playbooks_location }}/apt_update_server.yml"

- name: Clone Ansible Repo
  ansible.builtin.git:
    repo: https://github.com/MatthewDavidMiller/ansible_configuration.git
    dest: "/ansible_configs/git/ansible_configuration"

- name: Clone Dns Repo
  ansible.builtin.git:
    repo: https://github.com/MatthewDavidMiller/DNS-Server-Configuration.git
    dest: "/ansible_configs/git/DNS-Server-Configuration"

- name: Clone VPN Repo
  ansible.builtin.git:
    repo: https://github.com/MatthewDavidMiller/VPN-Server-Configuration.git
    dest: "/ansible_configs/git/VPN-Server-Configuration"
