---
- name: Update Ubuntu packages
  hosts: ubuntu

  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
        update_cache: "yes"
      when: ansible_facts['distribution'] == 'Ubuntu'
